
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_NAME}?&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  access-secret: ${JWT_ACCESS}
  refresh-secret: ${JWT_REFRESH}
  time:
    access-expiration: ${ACCESS_EXP}
    refresh-expiration: ${REFRESH_EXP}